//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMS_Falcotelo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBStudentMS_FalcoteloEntities : DbContext
    {
        public DBStudentMS_FalcoteloEntities()
            : base("name=DBStudentMS_FalcoteloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAssignedSubject> tblAssignedSubject { get; set; }
        public virtual DbSet<tblCourse> tblCourse { get; set; }
        public virtual DbSet<tblStudent> tblStudent { get; set; }
        public virtual DbSet<tblSubject> tblSubject { get; set; }
        public virtual DbSet<vwStudentRecord> vwStudentRecord { get; set; }
    }
}
