//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMS_Falcotelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudentRecord
    {
        public int StudentNumber { get; set; }
        public string FullName { get; set; }
        public string Course { get; set; }
        public Nullable<int> TotalSubject { get; set; }
    }
}
